// Версия синтаксиса .proto
// proto3 - самый актуальный
// Должен быть первой строкой

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: internal/proto/chess.proto

// package — логическое пространство имён для типов в этом файле.
// Защищает от конфликтов имён при нескольких .proto. НЕ связано с Go-пакетом.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enum - перечисление, аналог const-набора
// В proto3 первое значение ОБЯЗАТЕЛЬНО = 0, это значение по умолчанию.
// Служит для отличия «значение не задано» от «задано явно».
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_WHITE             Color = 1
	Color_BLACK             Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "WHITE",
		2: "BLACK",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"WHITE":             1,
		"BLACK":             2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_chess_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_internal_proto_chess_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{0}
}

type PieceType int32

const (
	PieceType_PIECE_TYPE_UNSPECIFIED PieceType = 0
	PieceType_PAWN                   PieceType = 1
	PieceType_ROOK                   PieceType = 2
	PieceType_KNIGHT                 PieceType = 3
	PieceType_BISHOP                 PieceType = 4
	PieceType_QUEEN                  PieceType = 5
	PieceType_KING                   PieceType = 6
)

// Enum value maps for PieceType.
var (
	PieceType_name = map[int32]string{
		0: "PIECE_TYPE_UNSPECIFIED",
		1: "PAWN",
		2: "ROOK",
		3: "KNIGHT",
		4: "BISHOP",
		5: "QUEEN",
		6: "KING",
	}
	PieceType_value = map[string]int32{
		"PIECE_TYPE_UNSPECIFIED": 0,
		"PAWN":                   1,
		"ROOK":                   2,
		"KNIGHT":                 3,
		"BISHOP":                 4,
		"QUEEN":                  5,
		"KING":                   6,
	}
)

func (x PieceType) Enum() *PieceType {
	p := new(PieceType)
	*p = x
	return p
}

func (x PieceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PieceType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_chess_proto_enumTypes[1].Descriptor()
}

func (PieceType) Type() protoreflect.EnumType {
	return &file_internal_proto_chess_proto_enumTypes[1]
}

func (x PieceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PieceType.Descriptor instead.
func (PieceType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{1}
}

// message — структура, аналог struct в Go.
// Каждое поле имеет уникальный номер, по нему поле передаётся
// по сети в бинарном виде. Номера нельзя переиспользовать.
type Piece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         Color                  `protobuf:"varint,1,opt,name=color,proto3,enum=chess.Color" json:"color,omitempty"`
	Type          PieceType              `protobuf:"varint,2,opt,name=type,proto3,enum=chess.PieceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Piece) Reset() {
	*x = Piece{}
	mi := &file_internal_proto_chess_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{0}
}

func (x *Piece) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Piece) GetType() PieceType {
	if x != nil {
		return x.Type
	}
	return PieceType_PIECE_TYPE_UNSPECIFIED
}

// optional — «поле может отсутствовать». В Go генерируется как указатель *T.
// Нужен, когда важно отличить «пусто» от «значение по умолчанию».
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         *Piece                 `protobuf:"bytes,1,opt,name=piece,proto3,oneof" json:"piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_internal_proto_chess_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetPiece() *Piece {
	if x != nil {
		return x.Piece
	}
	return nil
}

// repeated — слайс/массив. В Go генерируется как []T. Может быть пустым.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_internal_proto_chess_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Grid          []*Row                 `protobuf:"bytes,3,rep,name=grid,proto3" json:"grid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_internal_proto_chess_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{3}
}

func (x *Board) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Board) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Board) GetGrid() []*Row {
	if x != nil {
		return x.Grid
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_internal_proto_chess_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        int32                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FromRow       int32                  `protobuf:"varint,3,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,4,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,5,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,6,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Captured      *Piece                 `protobuf:"bytes,7,opt,name=captured,proto3,oneof" json:"captured,omitempty"`
	Promotion     PieceType              `protobuf:"varint,8,opt,name=promotion,proto3,enum=chess.PieceType" json:"promotion,omitempty"`
	MovedPiece    *Piece                 `protobuf:"bytes,9,opt,name=moved_piece,json=movedPiece,proto3,oneof" json:"moved_piece,omitempty"`
	Check         bool                   `protobuf:"varint,10,opt,name=check,proto3" json:"check,omitempty"`
	Mate          bool                   `protobuf:"varint,11,opt,name=mate,proto3" json:"mate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_internal_proto_chess_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{5}
}

func (x *Move) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Move) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Move) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *Move) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *Move) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *Move) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *Move) GetCaptured() *Piece {
	if x != nil {
		return x.Captured
	}
	return nil
}

func (x *Move) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_PIECE_TYPE_UNSPECIFIED
}

func (x *Move) GetMovedPiece() *Piece {
	if x != nil {
		return x.MovedPiece
	}
	return nil
}

func (x *Move) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *Move) GetMate() bool {
	if x != nil {
		return x.Mate
	}
	return false
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1       *Player                `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       *Player                `protobuf:"bytes,3,opt,name=player2,proto3" json:"player2,omitempty"`
	Player1Color  Color                  `protobuf:"varint,4,opt,name=player1_color,json=player1Color,proto3,enum=chess.Color" json:"player1_color,omitempty"`
	Player2Color  Color                  `protobuf:"varint,5,opt,name=player2_color,json=player2Color,proto3,enum=chess.Color" json:"player2_color,omitempty"`
	Board         *Board                 `protobuf:"bytes,6,opt,name=board,proto3" json:"board,omitempty"`
	Current       Color                  `protobuf:"varint,7,opt,name=current,proto3,enum=chess.Color" json:"current,omitempty"`
	Moves         []*Move                `protobuf:"bytes,8,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_internal_proto_chess_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{6}
}

func (x *Game) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Game) GetPlayer1() *Player {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *Game) GetPlayer2() *Player {
	if x != nil {
		return x.Player2
	}
	return nil
}

func (x *Game) GetPlayer1Color() Color {
	if x != nil {
		return x.Player1Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Game) GetPlayer2Color() Color {
	if x != nil {
		return x.Player2Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Game) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Game) GetCurrent() Color {
	if x != nil {
		return x.Current
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Game) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersRequest) Reset() {
	*x = ListPlayersRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersRequest) ProtoMessage() {}

func (x *ListPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersRequest.ProtoReflect.Descriptor instead.
func (*ListPlayersRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{9}
}

type ListPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersResponse) Reset() {
	*x = ListPlayersResponse{}
	mi := &file_internal_proto_chess_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersResponse) ProtoMessage() {}

func (x *ListPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersResponse.ProtoReflect.Descriptor instead.
func (*ListPlayersResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{10}
}

func (x *ListPlayersResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlayerRequest) Reset() {
	*x = DeletePlayerRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlayerRequest) ProtoMessage() {}

func (x *DeletePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlayerRequest.ProtoReflect.Descriptor instead.
func (*DeletePlayerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlayerResponse) Reset() {
	*x = DeletePlayerResponse{}
	mi := &file_internal_proto_chess_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlayerResponse) ProtoMessage() {}

func (x *DeletePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlayerResponse.ProtoReflect.Descriptor instead.
func (*DeletePlayerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{13}
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1Name   string                 `protobuf:"bytes,1,opt,name=player1_name,json=player1Name,proto3" json:"player1_name,omitempty"`
	Player2Name   string                 `protobuf:"bytes,2,opt,name=player2_name,json=player2Name,proto3" json:"player2_name,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGameRequest) GetPlayer1Name() string {
	if x != nil {
		return x.Player1Name
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer2Name() string {
	if x != nil {
		return x.Player2Name
	}
	return ""
}

func (x *CreateGameRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CreateGameRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{15}
}

func (x *GetGameRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{16}
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_internal_proto_chess_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{17}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type UpdateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1Name   string                 `protobuf:"bytes,2,opt,name=player1_name,json=player1Name,proto3" json:"player1_name,omitempty"`
	Player2Name   string                 `protobuf:"bytes,3,opt,name=player2_name,json=player2Name,proto3" json:"player2_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameRequest) Reset() {
	*x = UpdateGameRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameRequest) ProtoMessage() {}

func (x *UpdateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateGameRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGameRequest) GetPlayer1Name() string {
	if x != nil {
		return x.Player1Name
	}
	return ""
}

func (x *UpdateGameRequest) GetPlayer2Name() string {
	if x != nil {
		return x.Player2Name
	}
	return ""
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteGameRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameResponse) Reset() {
	*x = DeleteGameResponse{}
	mi := &file_internal_proto_chess_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameResponse) ProtoMessage() {}

func (x *DeleteGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{20}
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FromRow       int32                  `protobuf:"varint,2,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,3,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,4,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,5,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Promotion     PieceType              `protobuf:"varint,6,opt,name=promotion,proto3,enum=chess.PieceType" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{21}
}

func (x *MakeMoveRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *MakeMoveRequest) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *MakeMoveRequest) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *MakeMoveRequest) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *MakeMoveRequest) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *MakeMoveRequest) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_PIECE_TYPE_UNSPECIFIED
}

type AutoMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoMoveRequest) Reset() {
	*x = AutoMoveRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoMoveRequest) ProtoMessage() {}

func (x *AutoMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoMoveRequest.ProtoReflect.Descriptor instead.
func (*AutoMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{22}
}

func (x *AutoMoveRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type CreateMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FromRow       int32                  `protobuf:"varint,2,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,3,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,4,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,5,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Promotion     PieceType              `protobuf:"varint,6,opt,name=promotion,proto3,enum=chess.PieceType" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMoveRequest) Reset() {
	*x = CreateMoveRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoveRequest) ProtoMessage() {}

func (x *CreateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoveRequest.ProtoReflect.Descriptor instead.
func (*CreateMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{23}
}

func (x *CreateMoveRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CreateMoveRequest) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *CreateMoveRequest) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *CreateMoveRequest) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *CreateMoveRequest) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *CreateMoveRequest) GetPromotion() PieceType {
	if x != nil {
		return x.Promotion
	}
	return PieceType_PIECE_TYPE_UNSPECIFIED
}

type GetMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoveRequest) Reset() {
	*x = GetMoveRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoveRequest) ProtoMessage() {}

func (x *GetMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoveRequest.ProtoReflect.Descriptor instead.
func (*GetMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{24}
}

func (x *GetMoveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMovesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovesResponse) Reset() {
	*x = ListMovesResponse{}
	mi := &file_internal_proto_chess_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovesResponse) ProtoMessage() {}

func (x *ListMovesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovesResponse.ProtoReflect.Descriptor instead.
func (*ListMovesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{25}
}

func (x *ListMovesResponse) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type UpdateMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        int32                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FromRow       int32                  `protobuf:"varint,3,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,4,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,5,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,6,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoveRequest) Reset() {
	*x = UpdateMoveRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoveRequest) ProtoMessage() {}

func (x *UpdateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoveRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateMoveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMoveRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *UpdateMoveRequest) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *UpdateMoveRequest) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *UpdateMoveRequest) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *UpdateMoveRequest) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

type DeleteMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMoveRequest) Reset() {
	*x = DeleteMoveRequest{}
	mi := &file_internal_proto_chess_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMoveRequest) ProtoMessage() {}

func (x *DeleteMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_chess_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMoveRequest.ProtoReflect.Descriptor instead.
func (*DeleteMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_chess_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteMoveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_internal_proto_chess_proto protoreflect.FileDescriptor

const file_internal_proto_chess_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/chess.proto\x12\x05chess\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\x05Piece\x12\"\n" +
	"\x05color\x18\x01 \x01(\x0e2\f.chess.ColorR\x05color\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.chess.PieceTypeR\x04type\"9\n" +
	"\x04Cell\x12'\n" +
	"\x05piece\x18\x01 \x01(\v2\f.chess.PieceH\x00R\x05piece\x88\x01\x01B\b\n" +
	"\x06_piece\"(\n" +
	"\x03Row\x12!\n" +
	"\x05cells\x18\x01 \x03(\v2\v.chess.CellR\x05cells\"O\n" +
	"\x05Board\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x1e\n" +
	"\x04grid\x18\x03 \x03(\v2\n" +
	".chess.RowR\x04grid\",\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xed\x02\n" +
	"\x04Move\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x05R\x06gameId\x12\x19\n" +
	"\bfrom_row\x18\x03 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x04 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x05 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x06 \x01(\x05R\x05toCol\x12-\n" +
	"\bcaptured\x18\a \x01(\v2\f.chess.PieceH\x00R\bcaptured\x88\x01\x01\x12.\n" +
	"\tpromotion\x18\b \x01(\x0e2\x10.chess.PieceTypeR\tpromotion\x122\n" +
	"\vmoved_piece\x18\t \x01(\v2\f.chess.PieceH\x01R\n" +
	"movedPiece\x88\x01\x01\x12\x14\n" +
	"\x05check\x18\n" +
	" \x01(\bR\x05check\x12\x12\n" +
	"\x04mate\x18\v \x01(\bR\x04mateB\v\n" +
	"\t_capturedB\x0e\n" +
	"\f_moved_piece\"\xbd\x02\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12'\n" +
	"\aplayer1\x18\x02 \x01(\v2\r.chess.PlayerR\aplayer1\x12'\n" +
	"\aplayer2\x18\x03 \x01(\v2\r.chess.PlayerR\aplayer2\x121\n" +
	"\rplayer1_color\x18\x04 \x01(\x0e2\f.chess.ColorR\fplayer1Color\x121\n" +
	"\rplayer2_color\x18\x05 \x01(\x0e2\f.chess.ColorR\fplayer2Color\x12\"\n" +
	"\x05board\x18\x06 \x01(\v2\f.chess.BoardR\x05board\x12&\n" +
	"\acurrent\x18\a \x01(\x0e2\f.chess.ColorR\acurrent\x12!\n" +
	"\x05moves\x18\b \x03(\v2\v.chess.MoveR\x05moves\")\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x14\n" +
	"\x12ListPlayersRequest\">\n" +
	"\x13ListPlayersResponse\x12'\n" +
	"\aplayers\x18\x01 \x03(\v2\r.chess.PlayerR\aplayers\"9\n" +
	"\x13UpdatePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"%\n" +
	"\x13DeletePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x16\n" +
	"\x14DeletePlayerResponse\"\x81\x01\n" +
	"\x11CreateGameRequest\x12!\n" +
	"\fplayer1_name\x18\x01 \x01(\tR\vplayer1Name\x12!\n" +
	"\fplayer2_name\x18\x02 \x01(\tR\vplayer2Name\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\x05R\x04cols\" \n" +
	"\x0eGetGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x12\n" +
	"\x10ListGamesRequest\"6\n" +
	"\x11ListGamesResponse\x12!\n" +
	"\x05games\x18\x01 \x03(\v2\v.chess.GameR\x05games\"i\n" +
	"\x11UpdateGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fplayer1_name\x18\x02 \x01(\tR\vplayer1Name\x12!\n" +
	"\fplayer2_name\x18\x03 \x01(\tR\vplayer2Name\"#\n" +
	"\x11DeleteGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x14\n" +
	"\x12DeleteGameResponse\"\xbe\x01\n" +
	"\x0fMakeMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x05R\x06gameId\x12\x19\n" +
	"\bfrom_row\x18\x02 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x03 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x04 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x05 \x01(\x05R\x05toCol\x12.\n" +
	"\tpromotion\x18\x06 \x01(\x0e2\x10.chess.PieceTypeR\tpromotion\"*\n" +
	"\x0fAutoMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x05R\x06gameId\"\xc0\x01\n" +
	"\x11CreateMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x05R\x06gameId\x12\x19\n" +
	"\bfrom_row\x18\x02 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x03 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x04 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x05 \x01(\x05R\x05toCol\x12.\n" +
	"\tpromotion\x18\x06 \x01(\x0e2\x10.chess.PieceTypeR\tpromotion\" \n" +
	"\x0eGetMoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"6\n" +
	"\x11ListMovesResponse\x12!\n" +
	"\x05moves\x18\x01 \x03(\v2\v.chess.MoveR\x05moves\"\xa0\x01\n" +
	"\x11UpdateMoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x05R\x06gameId\x12\x19\n" +
	"\bfrom_row\x18\x03 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x04 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x05 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x06 \x01(\x05R\x05toCol\"#\n" +
	"\x11DeleteMoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id*4\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05WHITE\x10\x01\x12\t\n" +
	"\x05BLACK\x10\x02*h\n" +
	"\tPieceType\x12\x1a\n" +
	"\x16PIECE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PAWN\x10\x01\x12\b\n" +
	"\x04ROOK\x10\x02\x12\n" +
	"\n" +
	"\x06KNIGHT\x10\x03\x12\n" +
	"\n" +
	"\x06BISHOP\x10\x04\x12\t\n" +
	"\x05QUEEN\x10\x05\x12\b\n" +
	"\x04KING\x10\x062\xc9\x02\n" +
	"\rPlayerService\x129\n" +
	"\fCreatePlayer\x12\x1a.chess.CreatePlayerRequest\x1a\r.chess.Player\x123\n" +
	"\tGetPlayer\x12\x17.chess.GetPlayerRequest\x1a\r.chess.Player\x12D\n" +
	"\vListPlayers\x12\x19.chess.ListPlayersRequest\x1a\x1a.chess.ListPlayersResponse\x129\n" +
	"\fUpdatePlayer\x12\x1a.chess.UpdatePlayerRequest\x1a\r.chess.Player\x12G\n" +
	"\fDeletePlayer\x12\x1a.chess.DeletePlayerRequest\x1a\x1b.chess.DeletePlayerResponse2\x8b\x03\n" +
	"\vGameService\x123\n" +
	"\n" +
	"CreateGame\x12\x18.chess.CreateGameRequest\x1a\v.chess.Game\x12-\n" +
	"\aGetGame\x12\x15.chess.GetGameRequest\x1a\v.chess.Game\x12>\n" +
	"\tListGames\x12\x17.chess.ListGamesRequest\x1a\x18.chess.ListGamesResponse\x123\n" +
	"\n" +
	"UpdateGame\x12\x18.chess.UpdateGameRequest\x1a\v.chess.Game\x12A\n" +
	"\n" +
	"DeleteGame\x12\x18.chess.DeleteGameRequest\x1a\x19.chess.DeleteGameResponse\x12/\n" +
	"\bMakeMove\x12\x16.chess.MakeMoveRequest\x1a\v.chess.Game\x12/\n" +
	"\bAutoMove\x12\x16.chess.AutoMoveRequest\x1a\v.chess.Game2\xa5\x02\n" +
	"\vMoveService\x123\n" +
	"\n" +
	"CreateMove\x12\x18.chess.CreateMoveRequest\x1a\v.chess.Move\x12-\n" +
	"\aGetMove\x12\x15.chess.GetMoveRequest\x1a\v.chess.Move\x12=\n" +
	"\tListMoves\x12\x16.google.protobuf.Empty\x1a\x18.chess.ListMovesResponse\x123\n" +
	"\n" +
	"UpdateMove\x12\x18.chess.UpdateMoveRequest\x1a\v.chess.Move\x12>\n" +
	"\n" +
	"DeleteMove\x12\x18.chess.DeleteMoveRequest\x1a\x16.google.protobuf.EmptyB\x1aZ\x18mod.go/internal/proto;pbb\x06proto3"

var (
	file_internal_proto_chess_proto_rawDescOnce sync.Once
	file_internal_proto_chess_proto_rawDescData []byte
)

func file_internal_proto_chess_proto_rawDescGZIP() []byte {
	file_internal_proto_chess_proto_rawDescOnce.Do(func() {
		file_internal_proto_chess_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_chess_proto_rawDesc), len(file_internal_proto_chess_proto_rawDesc)))
	})
	return file_internal_proto_chess_proto_rawDescData
}

var file_internal_proto_chess_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_chess_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_internal_proto_chess_proto_goTypes = []any{
	(Color)(0),                   // 0: chess.Color
	(PieceType)(0),               // 1: chess.PieceType
	(*Piece)(nil),                // 2: chess.Piece
	(*Cell)(nil),                 // 3: chess.Cell
	(*Row)(nil),                  // 4: chess.Row
	(*Board)(nil),                // 5: chess.Board
	(*Player)(nil),               // 6: chess.Player
	(*Move)(nil),                 // 7: chess.Move
	(*Game)(nil),                 // 8: chess.Game
	(*CreatePlayerRequest)(nil),  // 9: chess.CreatePlayerRequest
	(*GetPlayerRequest)(nil),     // 10: chess.GetPlayerRequest
	(*ListPlayersRequest)(nil),   // 11: chess.ListPlayersRequest
	(*ListPlayersResponse)(nil),  // 12: chess.ListPlayersResponse
	(*UpdatePlayerRequest)(nil),  // 13: chess.UpdatePlayerRequest
	(*DeletePlayerRequest)(nil),  // 14: chess.DeletePlayerRequest
	(*DeletePlayerResponse)(nil), // 15: chess.DeletePlayerResponse
	(*CreateGameRequest)(nil),    // 16: chess.CreateGameRequest
	(*GetGameRequest)(nil),       // 17: chess.GetGameRequest
	(*ListGamesRequest)(nil),     // 18: chess.ListGamesRequest
	(*ListGamesResponse)(nil),    // 19: chess.ListGamesResponse
	(*UpdateGameRequest)(nil),    // 20: chess.UpdateGameRequest
	(*DeleteGameRequest)(nil),    // 21: chess.DeleteGameRequest
	(*DeleteGameResponse)(nil),   // 22: chess.DeleteGameResponse
	(*MakeMoveRequest)(nil),      // 23: chess.MakeMoveRequest
	(*AutoMoveRequest)(nil),      // 24: chess.AutoMoveRequest
	(*CreateMoveRequest)(nil),    // 25: chess.CreateMoveRequest
	(*GetMoveRequest)(nil),       // 26: chess.GetMoveRequest
	(*ListMovesResponse)(nil),    // 27: chess.ListMovesResponse
	(*UpdateMoveRequest)(nil),    // 28: chess.UpdateMoveRequest
	(*DeleteMoveRequest)(nil),    // 29: chess.DeleteMoveRequest
	(*emptypb.Empty)(nil),        // 30: google.protobuf.Empty
}
var file_internal_proto_chess_proto_depIdxs = []int32{
	0,  // 0: chess.Piece.color:type_name -> chess.Color
	1,  // 1: chess.Piece.type:type_name -> chess.PieceType
	2,  // 2: chess.Cell.piece:type_name -> chess.Piece
	3,  // 3: chess.Row.cells:type_name -> chess.Cell
	4,  // 4: chess.Board.grid:type_name -> chess.Row
	2,  // 5: chess.Move.captured:type_name -> chess.Piece
	1,  // 6: chess.Move.promotion:type_name -> chess.PieceType
	2,  // 7: chess.Move.moved_piece:type_name -> chess.Piece
	6,  // 8: chess.Game.player1:type_name -> chess.Player
	6,  // 9: chess.Game.player2:type_name -> chess.Player
	0,  // 10: chess.Game.player1_color:type_name -> chess.Color
	0,  // 11: chess.Game.player2_color:type_name -> chess.Color
	5,  // 12: chess.Game.board:type_name -> chess.Board
	0,  // 13: chess.Game.current:type_name -> chess.Color
	7,  // 14: chess.Game.moves:type_name -> chess.Move
	6,  // 15: chess.ListPlayersResponse.players:type_name -> chess.Player
	8,  // 16: chess.ListGamesResponse.games:type_name -> chess.Game
	1,  // 17: chess.MakeMoveRequest.promotion:type_name -> chess.PieceType
	1,  // 18: chess.CreateMoveRequest.promotion:type_name -> chess.PieceType
	7,  // 19: chess.ListMovesResponse.moves:type_name -> chess.Move
	9,  // 20: chess.PlayerService.CreatePlayer:input_type -> chess.CreatePlayerRequest
	10, // 21: chess.PlayerService.GetPlayer:input_type -> chess.GetPlayerRequest
	11, // 22: chess.PlayerService.ListPlayers:input_type -> chess.ListPlayersRequest
	13, // 23: chess.PlayerService.UpdatePlayer:input_type -> chess.UpdatePlayerRequest
	14, // 24: chess.PlayerService.DeletePlayer:input_type -> chess.DeletePlayerRequest
	16, // 25: chess.GameService.CreateGame:input_type -> chess.CreateGameRequest
	17, // 26: chess.GameService.GetGame:input_type -> chess.GetGameRequest
	18, // 27: chess.GameService.ListGames:input_type -> chess.ListGamesRequest
	20, // 28: chess.GameService.UpdateGame:input_type -> chess.UpdateGameRequest
	21, // 29: chess.GameService.DeleteGame:input_type -> chess.DeleteGameRequest
	23, // 30: chess.GameService.MakeMove:input_type -> chess.MakeMoveRequest
	24, // 31: chess.GameService.AutoMove:input_type -> chess.AutoMoveRequest
	25, // 32: chess.MoveService.CreateMove:input_type -> chess.CreateMoveRequest
	26, // 33: chess.MoveService.GetMove:input_type -> chess.GetMoveRequest
	30, // 34: chess.MoveService.ListMoves:input_type -> google.protobuf.Empty
	28, // 35: chess.MoveService.UpdateMove:input_type -> chess.UpdateMoveRequest
	29, // 36: chess.MoveService.DeleteMove:input_type -> chess.DeleteMoveRequest
	6,  // 37: chess.PlayerService.CreatePlayer:output_type -> chess.Player
	6,  // 38: chess.PlayerService.GetPlayer:output_type -> chess.Player
	12, // 39: chess.PlayerService.ListPlayers:output_type -> chess.ListPlayersResponse
	6,  // 40: chess.PlayerService.UpdatePlayer:output_type -> chess.Player
	15, // 41: chess.PlayerService.DeletePlayer:output_type -> chess.DeletePlayerResponse
	8,  // 42: chess.GameService.CreateGame:output_type -> chess.Game
	8,  // 43: chess.GameService.GetGame:output_type -> chess.Game
	19, // 44: chess.GameService.ListGames:output_type -> chess.ListGamesResponse
	8,  // 45: chess.GameService.UpdateGame:output_type -> chess.Game
	22, // 46: chess.GameService.DeleteGame:output_type -> chess.DeleteGameResponse
	8,  // 47: chess.GameService.MakeMove:output_type -> chess.Game
	8,  // 48: chess.GameService.AutoMove:output_type -> chess.Game
	7,  // 49: chess.MoveService.CreateMove:output_type -> chess.Move
	7,  // 50: chess.MoveService.GetMove:output_type -> chess.Move
	27, // 51: chess.MoveService.ListMoves:output_type -> chess.ListMovesResponse
	7,  // 52: chess.MoveService.UpdateMove:output_type -> chess.Move
	30, // 53: chess.MoveService.DeleteMove:output_type -> google.protobuf.Empty
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_proto_chess_proto_init() }
func file_internal_proto_chess_proto_init() {
	if File_internal_proto_chess_proto != nil {
		return
	}
	file_internal_proto_chess_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_proto_chess_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_chess_proto_rawDesc), len(file_internal_proto_chess_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_proto_chess_proto_goTypes,
		DependencyIndexes: file_internal_proto_chess_proto_depIdxs,
		EnumInfos:         file_internal_proto_chess_proto_enumTypes,
		MessageInfos:      file_internal_proto_chess_proto_msgTypes,
	}.Build()
	File_internal_proto_chess_proto = out.File
	file_internal_proto_chess_proto_goTypes = nil
	file_internal_proto_chess_proto_depIdxs = nil
}
